name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Generate coverage report
        run: ./gradlew :jhu-seclab-cobra-commons-value:test :jhu-seclab-cobra-commons-value:koverXmlReport

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./commons-value/build/reports/kover/report.xml